@startuml
package "TreQ.TIL.RangeExpressions.Numeric" {
    class NumericAverageOver  {
        + Source : NumericRangeExpression 
        + BufferDimensions : int[] 
        + AveragingAxis : int 
    }
}
@enduml
