graph TD
    Frame1["Frame"]
    Interval1["100 ns"]
    Waveform1["ConstantWaveform"]
    Waveform1 -- "Duration" --- Interval1
    Instruction2["ModulatedPulse"]
    Instruction2 -- "Frame" --- Frame1
    Instruction2 -- "Envelope" --- Waveform1
    Radians2["1 rad"]
    Instruction2 -- "PhaseOffset" --- Radians2
    Instruction3["ModulatedPulse"]
    Instruction3 -- "Frame" --- Frame1
    Instruction3 -- "Envelope" --- Waveform1
    Radians3["1 rad"]
    Instruction3 -- "PhaseOffset" --- Radians3
    Instruction4:Alignment["EndToStart"]
    Instruction4:Relationship["InstructionRelationship"]
    Instruction4:Relationship -- "Alignment" --- Instruction4:Alignment
    Instruction4["Dependency"]
    Instruction4 -- "Relationship" --- Instruction4:Relationship
    Instruction4 -- "Lhs" --- Instruction2
    Instruction4 -- "Rhs" --- Instruction3
    Frame2["Frame"]
    Interval4["150 ns"]
    Waveform2["ConstantWaveform"]
    Waveform2 -- "Duration" --- Interval4
    Instruction6["ModulatedPulse"]
    Instruction6 -- "Frame" --- Frame2
    Instruction6 -- "Envelope" --- Waveform2
    Radians5["2 rad"]
    Instruction6 -- "PhaseOffset" --- Radians5
    Instruction7["ModulatedPulse"]
    Instruction7 -- "Frame" --- Frame2
    Instruction7 -- "Envelope" --- Waveform2
    Radians6["2 rad"]
    Instruction7 -- "PhaseOffset" --- Radians6
    Instruction8:Alignment["EndToStart"]
    Instruction8:Relationship["InstructionRelationship"]
    Instruction8:Relationship -- "Alignment" --- Instruction8:Alignment
    Instruction8["Dependency"]
    Instruction8 -- "Relationship" --- Instruction8:Relationship
    Instruction8 -- "Lhs" --- Instruction6
    Instruction8 -- "Rhs" --- Instruction7
    Frame3["Frame"]
    Interval7["50 ns"]
    Waveform3["ConstantWaveform"]
    Waveform3 -- "Duration" --- Interval7
    Instruction10["ModulatedPulse"]
    Instruction10 -- "Frame" --- Frame3
    Instruction10 -- "Envelope" --- Waveform3
    Radians8["3 rad"]
    Instruction10 -- "PhaseOffset" --- Radians8
    Instruction11["ModulatedPulse"]
    Instruction11 -- "Frame" --- Frame3
    Instruction11 -- "Envelope" --- Waveform3
    Radians9["3 rad"]
    Instruction11 -- "PhaseOffset" --- Radians9
    Instruction12:Alignment["EndToStart"]
    Instruction12:Relationship["InstructionRelationship"]
    Instruction12:Relationship -- "Alignment" --- Instruction12:Alignment
    Instruction12["Dependency"]
    Instruction12 -- "Relationship" --- Instruction12:Relationship
    Instruction12 -- "Lhs" --- Instruction10
    Instruction12 -- "Rhs" --- Instruction11
    Instruction14["ModulatedPulse"]
    Instruction14 -- "Frame" --- Frame1
    Instruction14 -- "Envelope" --- Waveform1
    Radians10["1 rad"]
    Instruction14 -- "PhaseOffset" --- Radians10
    Instruction15["ModulatedPulse"]
    Instruction15 -- "Frame" --- Frame2
    Instruction15 -- "Envelope" --- Waveform2
    Radians11["2 rad"]
    Instruction15 -- "PhaseOffset" --- Radians11
    Instruction16:Alignment["EndToStart"]
    Instruction16:Relationship["InstructionRelationship"]
    Instruction16:Relationship -- "Alignment" --- Instruction16:Alignment
    Instruction16["Dependency"]
    Instruction16 -- "Relationship" --- Instruction16:Relationship
    Instruction16 -- "Lhs" --- Instruction14
    Instruction16 -- "Rhs" --- Instruction15
    Instruction18["ModulatedPulse"]
    Instruction18 -- "Frame" --- Frame2
    Instruction18 -- "Envelope" --- Waveform2
    Radians12["2 rad"]
    Instruction18 -- "PhaseOffset" --- Radians12
    Instruction19["ModulatedPulse"]
    Instruction19 -- "Frame" --- Frame1
    Instruction19 -- "Envelope" --- Waveform1
    Radians13["1 rad"]
    Instruction19 -- "PhaseOffset" --- Radians13
    Instruction20:Alignment["EndToStart"]
    Instruction20:Relationship["InstructionRelationship"]
    Instruction20:Relationship -- "Alignment" --- Instruction20:Alignment
    Instruction20["Dependency"]
    Instruction20 -- "Relationship" --- Instruction20:Relationship
    Instruction20 -- "Lhs" --- Instruction18
    Instruction20 -- "Rhs" --- Instruction19
    Instruction22["ModulatedPulse"]
    Instruction22 -- "Frame" --- Frame1
    Instruction22 -- "Envelope" --- Waveform1
    Radians14["1 rad"]
    Instruction22 -- "PhaseOffset" --- Radians14
    Instruction23["ModulatedPulse"]
    Instruction23 -- "Frame" --- Frame3
    Instruction23 -- "Envelope" --- Waveform3
    Radians15["3 rad"]
    Instruction23 -- "PhaseOffset" --- Radians15
    Instruction24:Alignment["EndToStart"]
    Instruction24:Relationship["InstructionRelationship"]
    Instruction24:Relationship -- "Alignment" --- Instruction24:Alignment
    Instruction24["Dependency"]
    Instruction24 -- "Relationship" --- Instruction24:Relationship
    Instruction24 -- "Lhs" --- Instruction22
    Instruction24 -- "Rhs" --- Instruction23
    Instruction26["ModulatedPulse"]
    Instruction26 -- "Frame" --- Frame3
    Instruction26 -- "Envelope" --- Waveform3
    Radians16["3 rad"]
    Instruction26 -- "PhaseOffset" --- Radians16
    Instruction27["ModulatedPulse"]
    Instruction27 -- "Frame" --- Frame1
    Instruction27 -- "Envelope" --- Waveform1
    Radians17["1 rad"]
    Instruction27 -- "PhaseOffset" --- Radians17
    Instruction28:Alignment["EndToStart"]
    Instruction28:Relationship["InstructionRelationship"]
    Instruction28:Relationship -- "Alignment" --- Instruction28:Alignment
    Instruction28["Dependency"]
    Instruction28 -- "Relationship" --- Instruction28:Relationship
    Instruction28 -- "Lhs" --- Instruction26
    Instruction28 -- "Rhs" --- Instruction27
