@startuml
package "TreQ.TIL.ValueExpressions.Numeric" {
    class BinaryNumericOperation  {
        + Operator : BinaryNumericOperators 
        + Lhs : NumericExpression 
        + Rhs : NumericExpression 
    }
}
@enduml
