@startuml
package "TreQ.TIL.RangeExpressions.Complex" {
    class ComplexAverageOver  {
        + Source : ComplexRangeExpression 
        + BufferDimensions : int[] 
        + AveragingAxis : int 
    }
}
@enduml
