@startuml
package "TreQ.TIL.Waveforms" {
    class SampledNumericWaveform  {
        + SampleInterval : Interval 
        + Samples : double[] 
    }
    class SampledComplexWaveform  {
        + SampleInterval : Interval 
        + Samples : Complex[] 
    }
}
@enduml
