@startuml
package "TreQ.TIL.Waveforms" {
    class SuddenNetZeroWaveform  {
        + Duration : Interval 
        + MidpointDelay : Interval 
        + BAmplitude : Amplitude 
        + BDuration : Interval 
    }
}
@enduml
