@startuml
package "TreQ.TIL.Instructions" {
    class DetuneFrame  {
        + Frame : Frame 
        + Detuning : Frequency 
        + Scope : Block 
        + PhaseReference : PhaseReferencePoints
    }
}
@enduml
