@startuml
package "TreQ.TIL.ValueExpressions.Complex" {
    class BinaryComplexOperation  {
        + Operator : BinaryComplexOperators 
        + Lhs : ComplexExpression 
        + Rhs : ComplexExpression 
    }
}
@enduml
