@startuml
package "TreQ.TIL.ValueExpressions.Complex" {
    class ComplexConditional  {
        + Guard : BooleanExpression 
        + TrueCase : ComplexExpression 
        + FalseCase : ComplexExpression 
    }
}
@enduml
